# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PublicSpeakingAPP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PublicSpeakingAPP
pod 'TensorFlowLiteSwift',        '0.0.1-nightly.20250619'
  pod 'TensorFlowLiteC',            '0.0.1-nightly.20250619'
  pod 'TensorFlowLiteSelectTfOps',  '0.0.1-nightly.20250619'
pod 'RiveRuntime'

  target 'PublicSpeakingAPPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PublicSpeakingAPPUITests' do
    # Pods for testing
  end

end
